import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { montserrat } from "@/lib/font";

export const metadata: Metadata = {
  title: "Votely",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const header = (
    <header>
      <Navbar />
    </header>
  );

  const footer = <Footer />;

  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
