/*
export const businesses = [
  {
    id: 1,
    name: "Boba Guys",
    category: "Coffee Shop",
    rating: 2.5,
    reviews: 120,
    location: "San Francisco",
    awards: ["Best of 2022", "Hall of Fame"],
    tags: ["Coffee", "Drinks", "Cozy"],
    image: "/businesses/coffee_purple.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 2,
    name: "Tartine Bakery",
    category: "Bakery",
    rating: 2.0,
    reviews: 250,
    location: "Los Angeles",
    awards: ["Best of 2022"],
    tags: ["Pastries", "Bakery", "Artisan"],
    image: "/businesses/kaffee.jpg",
    featured: true,
    topRated: false,
  },
  {
    id: 3,
    name: "Golden Gate Park",
    category: "Park",
    rating: 4.7,
    reviews: 430,
    location: "San Francisco",
    awards: ["Best New"],
    tags: ["Nature", "Outdoor", "Relaxation"],
    image: "/businesses/hotel_3.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 4,
    name: "Blue Bottle Coffee",
    category: "Coffee Shop",
    rating: 4.6,
    reviews: 300,
    location: "New York",
    awards: ["Hall of Fame"],
    tags: ["Coffee", "Drinks", "Modern"],
    image: "/businesses/cartier.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 5,
    name: "Rich Table",
    category: "Restaurant",
    rating: 4.9,
    reviews: 500,
    location: "Chicago",
    awards: ["Best of 2022"],
    tags: ["Fine Dining", "Innovative", "High-End"],
    image: "/businesses/hotel_1.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 6,
    name: "Sunshine Spa",
    category: "Spa & Wellness",
    rating: 4.3,
    reviews: 200,
    location: "Miami",
    awards: ["Top Relaxation Spot"],
    tags: ["Wellness", "Relaxation", "Luxury"],
    image: "/businesses/hotel_5.jpg",
    featured: false,
    topRated: false,
  },
  {
    id: 7,
    name: "Green Leaf Market",
    category: "Grocery Store",
    rating: 4.5,
    reviews: 150,
    location: "Austin",
    awards: ["Sustainable Business Award"],
    tags: ["Organic", "Groceries", "Eco-Friendly"],
    image: "/businesses/tiffany_co.jpg",
    featured: true,
    topRated: false,
  },
  {
    id: 8,
    name: "Artisan Pizza Co.",
    category: "Restaurant",
    rating: 4.8,
    reviews: 340,
    location: "Seattle",
    awards: ["Top Pizza Award"],
    tags: ["Pizza", "Casual Dining", "Family Friendly"],
    image: "/businesses/hotel_2.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 9,
    name: "PENO Tech World",
    category: "Electronics Store",
    rating: 4.7,
    reviews: 420,
    location: "Silicon Valley",
    awards: ["Tech Innovator Award"],
    tags: ["Electronics", "Innovation", "Technology"],
    image: "/businesses/peno.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 10,
    name: "Coastal Getaway Hotel",
    category: "Hotel",
    rating: 3.0,
    reviews: 600,
    location: "San Diego",
    awards: ["Top Coastal Retreat"],
    tags: ["Beach", "Luxury", "Relaxation"],
    image: "/businesses/hotel_4.jpg",
    featured: false,
    topRated: false,
  },
  {
    id: 11,
    name: "HiM Downtown Gym",
    category: "Fitness Center",
    rating: 3.6,
    reviews: 320,
    location: "Denver",
    awards: ["Best Fitness Facility"],
    tags: ["Fitness", "Health", "Strength"],
    image: "/businesses/him.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 12,
    name: "Premier Inn",
    category: "Florist",
    rating: 4.4,
    reviews: 170,
    location: "Portland",
    awards: ["Top Florist of the Year"],
    tags: ["Flowers", "Decor", "Gifts"],
    image: "/businesses/premier_inn.jpg",
    featured: true,
    topRated: false,
  },
  {
    id: 13,
    name: "Fish & Chips",
    category: "Restaurant",
    rating: 4.9,
    reviews: 540,
    location: "Boston",
    awards: ["Best Chef Award"],
    tags: ["Fine Dining", "Cuisine", "Luxury"],
    image: "/businesses/fish_chips.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 14,
    name: "City Books",
    category: "Bookstore",
    rating: 2.7,
    reviews: 310,
    location: "Philadelphia",
    awards: ["Readers' Choice Award"],
    tags: ["Books", "Culture", "Relaxation"],
    image: "/businesses/sega.jpg",
    featured: false,
    topRated: false,
  },
  {
    id: 15,
    name: "Urban Art Gallery",
    category: "Art Gallery",
    rating: 5.0,
    reviews: 400,
    location: "New Orleans",
    awards: ["Cultural Excellence Award"],
    tags: ["Art", "Exhibitions", "Culture"],
    image: "/businesses/shop_1.jpg",
    featured: true,
    topRated: true,
  },
];
*/

export const businesses = [
  {
    id: 1,
    name: "Boba Guys",
    category: "Coffee Shop",
    rating: 2.5,
    reviews: 120,
    location: "Kampala",
    awards: ["Best of 2022", "Hall of Fame"],
    tags: ["Coffee", "Drinks", "Cozy"],
    image: "/businesses/coffee_purple.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 2,
    name: "Tartine Bakery",
    category: "Bakery",
    rating: 2.0,
    reviews: 250,
    location: "Entebbe",
    awards: ["Best of 2022"],
    tags: ["Pastries", "Bakery", "Artisan"],
    image: "/businesses/kaffee.jpg",
    featured: true,
    topRated: false,
  },
  {
    id: 3,
    name: "Golden Gate Park",
    category: "Park",
    rating: 4.7,
    reviews: 430,
    location: "Mbarara",
    awards: ["Best New"],
    tags: ["Nature", "Outdoor", "Relaxation"],
    image: "/businesses/hotel_3.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 4,
    name: "Blue Bottle Coffee",
    category: "Coffee Shop",
    rating: 4.6,
    reviews: 300,
    location: "Fort Portal",
    awards: ["Hall of Fame"],
    tags: ["Coffee", "Drinks", "Modern"],
    image: "/businesses/cartier.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 5,
    name: "Rich Table",
    category: "Restaurant",
    rating: 4.9,
    reviews: 500,
    location: "Jinja",
    awards: ["Best of 2022"],
    tags: ["Fine Dining", "Innovative", "High-End"],
    image: "/businesses/hotel_1.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 6,
    name: "Sunshine Spa",
    category: "Spa & Wellness",
    rating: 4.3,
    reviews: 200,
    location: "Kampala",
    awards: ["Top Relaxation Spot"],
    tags: ["Wellness", "Relaxation", "Luxury"],
    image: "/businesses/hotel_5.jpg",
    featured: false,
    topRated: false,
  },
  {
    id: 7,
    name: "Green Leaf Market",
    category: "Grocery Store",
    rating: 4.5,
    reviews: 150,
    location: "Entebbe",
    awards: ["Sustainable Business Award"],
    tags: ["Organic", "Groceries", "Eco-Friendly"],
    image: "/businesses/tiffany_co.jpg",
    featured: true,
    topRated: false,
  },
  {
    id: 8,
    name: "Artisan Pizza Co.",
    category: "Restaurant",
    rating: 4.8,
    reviews: 340,
    location: "Mbarara",
    awards: ["Top Pizza Award"],
    tags: ["Pizza", "Casual Dining", "Family Friendly"],
    image: "/businesses/hotel_2.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 9,
    name: "PENO Tech World",
    category: "Electronics Store",
    rating: 4.7,
    reviews: 420,
    location: "Fort Portal",
    awards: ["Tech Innovator Award"],
    tags: ["Electronics", "Innovation", "Technology"],
    image: "/businesses/peno.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 10,
    name: "Coastal Getaway Hotel",
    category: "Hotel",
    rating: 3.0,
    reviews: 600,
    location: "Jinja",
    awards: ["Top Coastal Retreat"],
    tags: ["Beach", "Luxury", "Relaxation"],
    image: "/businesses/hotel_4.jpg",
    featured: false,
    topRated: false,
  },
  {
    id: 11,
    name: "HiM Downtown Gym",
    category: "Fitness Center",
    rating: 3.6,
    reviews: 320,
    location: "Kampala",
    awards: ["Best Fitness Facility"],
    tags: ["Fitness", "Health", "Strength"],
    image: "/businesses/him.jpg",
    featured: false,
    topRated: true,
  },
  {
    id: 12,
    name: "Premier Inn",
    category: "Florist",
    rating: 5.0,
    reviews: 170,
    location: "Entebbe",
    awards: ["Top Florist of the Year"],
    tags: ["Flowers", "Decor", "Gifts"],
    image: "/businesses/premier_inn.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 13,
    name: "Fish & Chips",
    category: "Restaurant",
    rating: 4.9,
    reviews: 540,
    location: "Mbarara",
    awards: ["Best Chef Award"],
    tags: ["Fine Dining", "Cuisine", "Luxury"],
    image: "/businesses/fish_chips.jpg",
    featured: true,
    topRated: true,
  },
  {
    id: 14,
    name: "City Books",
    category: "Bookstore",
    rating: 2.7,
    reviews: 310,
    location: "Fort Portal",
    awards: ["Readers' Choice Award"],
    tags: ["Books", "Culture", "Relaxation"],
    image: "/businesses/sega.jpg",
    featured: false,
    topRated: false,
  },
  {
    id: 15,
    name: "Urban Art Gallery",
    category: "Art Gallery",
    rating: 5.0,
    reviews: 400,
    location: "Jinja",
    awards: ["Cultural Excellence Award"],
    tags: ["Art", "Exhibitions", "Culture"],
    image: "/businesses/shop_1.jpg",
    featured: true,
    topRated: true,
  },
];
